const pages = {
    welcome: document.getElementById("welcomePage"),
    mode: document.getElementById("modePage"),
    game: document.getElementById("gamePage"),
    teamSetup: document.getElementById("teamSetupPage"),
    teamWordInput: document.getElementById("teamWordInputPage"),
    teamResult: document.getElementById("teamResultPage"),
    theme: document.getElementById("themePage")
  };
  
  const els = {
    instructionsSection: document.getElementById("instructionsSection"),
    settingsSection: document.getElementById("settingsSection"),
    scoreSection: document.getElementById("scoreSection"),
    welcomeContent: document.getElementById("welcomeContent"),
    wordDisplay: document.getElementById("wordDisplay"),
    keyboard: document.getElementById("keyboard"),
    gameStatus: document.getElementById("gameStatus"),
    scoreLabel: document.getElementById("scoreLabel"),
    scoreValue: document.getElementById("scoreValue"),
    highScoreLabel: document.getElementById("highScoreLabel"),
    highScoreValue: document.getElementById("highScoreValue"),
    livesValue: document.getElementById("livesValue"),
    gameTimer: document.getElementById("gameTimer"),
    hintText: document.getElementById("hintText"),
    resultModal: document.getElementById("resultModal"),
    resultEmoji: document.getElementById("resultEmoji"),
    resultTitle: document.getElementById("resultTitle"),
    resultMessage: document.getElementById("resultMessage"),
    correctWord: document.getElementById("correctWord"),
    welcomeHighScore: document.getElementById("welcomeHighScore"),
    playButton: document.getElementById("playButton"),
    hangmanParts: [
      document.getElementById("head"),
      document.getElementById("body"),
      document.getElementById("leftArm"),
      document.getElementById("rightArm"),
      document.getElementById("leftLeg"),
      document.getElementById("rightLeg")
    ],
    musicVolume: document.getElementById("musicVolume"),
    soundFxVolume: document.getElementById("soundFxVolume"),
    slider: document.querySelector("#instructionsSlider .slider"),
    prevSlideBtn: document.getElementById("prevSlideBtn"),
    nextSlideBtn: document.getElementById("nextSlideBtn"),
    currentInstruction: document.getElementById("currentInstruction"),
    playAgainButton: document.getElementById("playAgainButton"),
    highScoreClassic: document.getElementById("highScoreClassic"),
    highScoreThemed: document.getElementById("highScoreThemed"),
    highScoreTimed: document.getElementById("highScoreTimed"),
    modeHighScoreClassic: document.getElementById("modeHighScoreClassic"),
    modeHighScoreThemed: document.getElementById("modeHighScoreThemed"),
    modeHighScoreTimed: document.getElementById("modeHighScoreTimed"),
    roundCount: document.getElementById("roundCount"),
    playStyle: document.getElementById("playStyle"),
    timerDuration: document.getElementById("timerDuration"),
    teamWordInputTitle: document.getElementById("teamWordInputTitle"),
    teamScores: document.getElementById("teamScores"),
    teamCustomWord: document.getElementById("teamCustomWord"),
    teamCustomHint: document.getElementById("teamCustomHint"),
    finalTeamScores: document.getElementById("finalTeamScores"),
    winnerAnnouncement: document.getElementById("winnerAnnouncement"),
    newGameButton: document.getElementById("newGameButton"),
    hintButton: document.getElementById("hintButton"),
    resumeModal: document.getElementById("resumeModal"),
    resumeModalTitle: document.getElementById("resumeModalTitle"),
    resumeModalMessage: document.getElementById("resumeModalMessage"),
    resumeGameButton: document.getElementById("resumeGameButton"),
    newGameButtonModal: document.getElementById("newGameButtonModal")
  };
  
  const sounds = {
    background: document.getElementById("backgroundMusic"),
    correct: document.getElementById("correctSound"),
    wrong: document.getElementById("wrongSound"),
    win: document.getElementById("winSound"),
    lose: document.getElementById("loseSound"),
    click: document.getElementById("clickSound"),
    hover: document.getElementById("hoverSound")
  };